// src/react/provider/ModuleProvider.tsx
import React, { ReactNode, useEffect } from 'react'
import { ModuleManagerFactory, ModuleType } from '../../core'
import { ModuleContext } from './ModuleContext'

interface ModuleProviderProps {
  module: ModuleType
  children: ReactNode
}

export const ModuleProvider = ({module, children}: ModuleProviderProps) => {
  useEffect(() => {
    let mounted = true

    const loadModuleAsync = async () => {
      const moduleManager = ModuleManagerFactory.getInstance()

      try {
        if (!moduleManager.isModuleLoaded(module)) {
          await moduleManager.loadModule(module)
        }
      } catch (error) {
        if (mounted) {
          console.error(`Error loading module ${module.name}:`, error)
        }
      }
    }

    loadModuleAsync()

    return () => {
      mounted = false
      ModuleManagerFactory.getInstance().unloadModule(module)
    }
  }, [module])

  return (
    <ModuleContext.Provider value={{moduleClass: module}}>
      {children}
    </ModuleContext.Provider>
  )
}

// src/vue3/components/ModuleProvider.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { ModuleManagerFactory, ModuleType } from '../../core'
import { provideModule } from '../context/moduleContext'

const props = defineProps<{
  module: ModuleType
}>()

provideModule(props.module)

onMounted(async () => {
  const moduleManager = ModuleManagerFactory.getInstance()

  try {
    if (!moduleManager.isModuleLoaded(props.module)) {
      await moduleManager.loadModule(props.module)
    }
  } catch (error) {
    console.error(`Error loading module ${props.module.name}:`, error)
  }
})

onUnmounted(() => {
  ModuleManagerFactory.getInstance().unloadModule(props.module)
})
</script>

<template>
<slot></slot>
</template>
